// Special word emoji trophies
// Words that award secret emoji trophies when discovered
// Organized by category for easier maintenance

const SPECIAL_WORD_TROPHIES = {
  // Animals - Mammals
  cats: "🐈‍⬛",
  cat: "🐈‍⬛",
  kitten: "🐈‍⬛",
  meow: "🐈‍⬛",
  dogs: "🐕",
  wolf: "🐺",
  foxes: "🦊",
  bear: "🐻",
  bears: "🐻",
  panda: "🐼",
  lion: "🦁",
  lions: "🦁",
  tiger: "🐯",
  cow: "🐄",
  cows: "🐄",
  pig: "🐷",
  pigs: "🐷",
  boar: "🐗",
  horse: "🐴",
  zebra: "🦓",
  deer: "🦌",
  bunny: "🐰",
  mouse: "🐭",
  mice: "🐭",
  rat: "🐀",
  rats: "🐀",
  koala: "🐨",
  sloth: "🦥",
  otter: "🦦",
  skunk: "🦨",
  camel: "🐫",
  llama: "🦙",
  goat: "🐐",
  goats: "🐐",
  ram: "🐏",
  sheep: "🐑",

  // Animals - Birds
  bird: "🐦",
  birds: "🐦",
  owl: "🦉",
  owls: "🦉",
  eagle: "🦅",
  duck: "🦆",
  ducks: "🦆",
  swan: "🦢",
  swans: "🦢",
  dove: "🕊️",
  doves: "🕊️",
  crow: "🐦‍⬛",
  raven: "🐦‍⬛",
  parrot: "🦜",
  peacock: "🦚",
  penguin: "🐧",
  chick: "🐥",
  rooster: "🐓",
  turkey: "🦃",
  flamingo: "🦩",

  // Animals - Sea creatures
  fish: "🐟",
  whale: "🐋",
  shark: "🦈",
  dolphin: "🐬",
  seal: "🦭",
  seals: "🦭",
  crab: "🦀",
  crabs: "🦀",
  lobster: "🦞",
  shrimp: "🦐",
  squid: "🦑",
  octopus: "🐙",

  // Animals - Reptiles & Amphibians
  frog: "🐸",
  frogs: "🐸",
  turtle: "🐢",
  lizard: "🦎",
  snake: "🐍",
  croc: "🐊",

  // Animals - Insects & Small creatures
  bug: "🐛",
  bugs: "🐛",
  ant: "🐜",
  ants: "🐜",
  bee: "🐝",
  bees: "🐝",
  beetle: "🪲",
  fly: "🪰",
  flies: "🪰",
  worm: "🪱",
  worms: "🪱",
  spider: "🕷️",
  snail: "🐌",
  butterfly: "🦋",
  cricket: "🦗",
  mosquito: "🦟",

  // Nature - Plants & Flowers
  rose: "🌹",
  roses: "🌹",
  tulip: "🌷",
  daisy: "🌼",
  bloom: "🌸",
  herb: "🌿",
  herbs: "🌿",
  leaf: "🍃",
  palm: "🌴",
  fern: "🌿",
  cactus: "🌵",
  tree: "🌳",
  trees: "🌳",
  pine: "🌲",
  bamboo: "🎋",
  shamrock: "☘️",
  clover: "🍀",

  // Nature - Weather & Sky
  sun: "☀️",
  moon: "🌙",
  star: "⭐",
  stars: "⭐",
  cloud: "☁️",
  rain: "🌧️",
  rains: "🌧️",
  snow: "❄️",
  storm: "⛈️",
  thunder: "⛈️",
  wind: "💨",
  winds: "💨",
  comet: "☄️",
  rainbow: "🌈",
  fire: "🔥",
  fires: "🔥",
  flame: "🔥",

  // Food - Fruits
  apple: "🍎",
  pear: "🍐",
  pears: "🍐",
  peach: "🍑",
  lemon: "🍋",
  lime: "🍋",
  melon: "🍉",
  grape: "🍇",
  cherry: "🍒",
  berry: "🫐",
  mango: "🥭",
  kiwi: "🥝",
  olive: "🫒",
  coconut: "🥥",

  // Food - Vegetables
  corn: "🌽",
  pepper: "🌶️",
  carrot: "🥕",
  tomato: "🍅",
  potato: "🥔",
  onion: "🧅",
  garlic: "🧄",
  peas: "🫛",
  broccoli: "🥦",
  lettuce: "🥬",
  cucumber: "🥒",
  pickle: "🥒",

  // Food - Other
  bread: "🍞",
  bagel: "🥯",
  croissant: "🥐",
  pretzel: "🥨",
  cheese: "🧀",
  meat: "🍖",
  bacon: "🥓",
  egg: "🥚",
  eggs: "🥚",
  pizza: "🍕",
  burger: "🍔",
  fries: "🍟",
  taco: "🌮",
  tacos: "🌮",
  burrito: "🌯",
  sushi: "🍣",
  ramen: "🍜",
  soup: "🍲",
  salad: "🥗",
  cookie: "🍪",
  cake: "🍰",
  cakes: "🍰",
  pie: "🥧",
  pies: "🥧",
  donut: "🍩",
  honey: "🍯",
  salt: "🧂",
  butter: "🧈",
  icecream: "🍦",
  popcorn: "🍿",
  candy: "🍬",

  // Drinks
  milk: "🥛",
  coffee: "☕",
  tea: "🍵",
  sake: "🍶",
  wine: "🍷",
  wines: "🍷",
  beer: "🍺",
  beers: "🍺",
  cocktail: "🍹",
  juice: "🧃",
  soda: "🥤",
  water: "💧",

  // Objects - Tools & Items
  hammer: "🔨",
  wrench: "🔧",
  saw: "🪚",
  screw: "🪛",
  drill: "🪛",
  axe: "🪓",
  magnet: "🧲",
  bomb: "💣",
  bombs: "💣",
  knife: "🔪",
  dagger: "🗡️",
  sword: "⚔️",
  bow: "🏹",
  shield: "🛡️",
  gun: "🔫",
  guns: "🔫",
  key: "🔑",
  keys: "🔑",
  lock: "🔒",
  chain: "⛓️",
  bell: "🔔",
  bells: "🔔",
  anchor: "⚓",

  // Objects - Household
  door: "🚪",
  doors: "🚪",
  window: "🪟",
  couch: "🛋️",
  bed: "🛏️",
  beds: "🛏️",
  bath: "🛁",
  toilet: "🚽",
  shower: "🚿",
  towel: "🧻",
  soap: "🧼",
  sponge: "🧽",
  broom: "🧹",
  basket: "🧺",
  candle: "🕯️",
  bulb: "💡",
  lamp: "🪔",
  lamps: "🪔",
  mirror: "🪞",
  window: "🪟",
  chair: "🪑",
  vase: "🏺",

  // Objects - Electronics & Entertainment
  phone: "📱",
  laptop: "💻",
  mouse: "🖱️",
  printer: "🖨️",
  camera: "📷",
  video: "📹",
  radio: "📻",
  clock: "🕐",
  watch: "⌚",
  alarm: "⏰",
  timer: "⏲️",
  hourglass: "⏳",

  // Objects - Office & School
  book: "📖",
  books: "📖",
  pen: "🖊️",
  pens: "🖊️",
  pencil: "✏️",
  crayon: "🖍️",
  ruler: "📏",
  scissors: "✂️",
  tape: "📼",
  clip: "📎",
  clips: "📎",
  pin: "📌",
  pins: "📌",
  folder: "📁",
  calendar: "📅",
  chart: "📊",
  graph: "📈",

  // Clothing & Accessories
  shirt: "👕",
  jeans: "👖",
  dress: "👗",
  coat: "🧥",
  coats: "🧥",
  socks: "🧦",
  glove: "🧤",
  scarf: "🧣",
  hat: "🎩",
  hats: "🎩",
  crown: "👑",
  ring: "💍",
  rings: "💍",
  gem: "💎",
  gems: "💎",
  purse: "👛",
  wallet: "👛",
  glasses: "👓",
  goggles: "🥽",
  tie: "👔",
  ties: "👔",
  boot: "🥾",
  boots: "🥾",
  sandal: "🩴",

  // Sports & Activities
  ball: "⚽",
  balls: "⚽",
  soccer: "⚽",
  baseball: "⚾",
  tennis: "🎾",
  rugby: "🏉",
  goal: "🥅",
  goals: "🥅",
  medal: "🏅",
  trophy: "🏆",
  ski: "🎿",
  skis: "🎿",
  sled: "🛷",
  kite: "🪁",
  kites: "🪁",
  pool: "🎱",
  dart: "🎯",
  darts: "🎯",
  bowling: "🎳",
  chess: "♟️",
  puzzle: "🧩",
  dice: "🎲",
  doll: "🪆",
  dolls: "🪆",
  yoyo: "🪀",

  // Music & Arts
  art: "🎨",
  arts: "🎨",
  paint: "🎨",
  brush: "🖌️",
  guitar: "🎸",
  violin: "🎻",
  drum: "🥁",
  drums: "🥁",
  trumpet: "🎺",
  piano: "🎹",
  mic: "🎤",
  music: "🎵",
  note: "🎵",
  notes: "🎵",
  song: "🎵",
  songs: "🎵",

  // Vehicles
  car: "🚗",
  cars: "🚗",
  taxi: "🚕",
  bus: "🚌",
  train: "🚂",
  tram: "🚊",
  truck: "🚚",
  van: "🚐",
  vans: "🚐",
  bike: "🚲",
  bikes: "🚲",
  scooter: "🛴",
  boat: "⛵",
  boats: "⛵",
  ship: "🚢",
  ships: "🚢",
  ferry: "⛴️",
  rocket: "🚀",
  plane: "✈️",
  helicopter: "🚁",
  parachute: "🪂",

  // Places & Buildings
  home: "🏠",
  homes: "🏠",
  house: "🏡",
  castle: "🏰",
  church: "⛪",
  mosque: "🕌",
  temple: "🛕",
  tent: "⛺",
  tents: "⛺",
  tower: "🗼",
  statue: "🗿",
  bridge: "🌉",
  fountain: "⛲",
  bank: "🏦",
  banks: "🏦",
  hotel: "🏨",
  school: "🏫",
  hospital: "🏥",
  factory: "🏭",

  // Symbols & Emotions
  heart: "❤️",
  love: "❤️",
  kiss: "💋",
  hug: "🤗",
  peace: "☮️",
  yin: "☯️",
  yang: "☯️",
  cross: "✝️",
  atom: "⚛️",
  warn: "⚠️",
  stop: "🛑",
  recycle: "♻️",
  check: "✅",
  flag: "🚩",
  flags: "🚩",

  // Professions & People
  cop: "👮",
  cops: "👮",
  guard: "💂",
  ninja: "🥷",
  pirate: "🏴‍☠️",
  mage: "🧙",
  fairy: "🧚",
  vampire: "🧛",
  zombie: "🧟",
  genie: "🧞",
  elf: "🧝",
  angel: "👼",
  santa: "🎅",
  clown: "🤡",
  prince: "🤴",
  king: "🤴",
  queen: "👸",
  baby: "👶",
  child: "🧒",
  boy: "👦",
  boys: "👦",
  girl: "👧",
  girls: "👧",
  man: "👨",
  men: "👨",
  woman: "👩",
  women: "👩",
  elder: "🧓",
  cook: "👨‍🍳",
  chef: "👨‍🍳",
  farmer: "👨‍🌾",
  doctor: "👨‍⚕️",
  student: "👨‍🎓",
  singer: "👨‍🎤",
  artist: "👨‍🎨",
  pilot: "👨‍✈️",

  // Body parts
  brain: "🧠",
  tooth: "🦷",
  teeth: "🦷",
  bone: "🦴",
  bones: "🦴",
  foot: "🦶",
  feet: "🦶",
  leg: "🦵",
  legs: "🦵",
  ear: "👂",
  ears: "👂",
  nose: "👃",
  eye: "👁️",
  eyes: "👁️",
  mouth: "👄",
  tongue: "👅",

  // Celebrations & Events
  party: "🎉",
  balloon: "🎈",
  gift: "🎁",
  gifts: "🎁",
  ribbon: "🎀",
  confetti: "🎊",
  firework: "🎆",
  sparkle: "✨",

  // Medical & Health
  pill: "💊",
  pills: "💊",
  bandage: "🩹",
  stethoscope: "🩺",
  syringe: "💉",
  droplet: "💧",
  blood: "🩸",

  // Miscellaneous
  magic: "✨",
  crystal: "🔮",
  ghost: "👻",
  alien: "👽",
  robot: "🤖",
  skull: "💀",
  poop: "💩",
  nerd: "🤓",
};

// Export for use in game.js
if (typeof module !== "undefined" && module.exports) {
  module.exports = SPECIAL_WORD_TROPHIES;
}
